name: Build Windows 64-bit Executable

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build 64-bit executable
      run: |
        pyinstaller --onefile --windowed --icon="pro.ico" --name "宽表转换工具-x64" pro2.py

    - name: Get version tag
      id: tag_version
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "TAG_VERSION=$(echo ${{ github.ref }} | sed -E 's/refs\/tags\/(.*)/\1/')" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_VERSION }}
        release_name: Release ${{ env.TAG_VERSION }}
        draft: false
        prerelease: false

    - name: Upload 64-bit Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/宽表转换工具-x64.exe
        asset_name: 宽表转换工具-x64.exe
        asset_content_type: application/vnd.microsoft.portable-executable
